# Generated by Django 5.0.1 on 2024-01-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0004_delete_blog_article_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Blog',
        ),
    ]
