# Generated by Django 5.0.1 on 2024-01-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0005_rename_article_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
    ]
